name: .NET Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet packages
      run: nuget restore RandomNumber2/RandomNumber2.csproj

    - name: Build solution
      run: msbuild RandomNumber2/RandomNumber2.csproj /p:Configuration=Release

    - name: Build test project
      run: msbuild RandomNumber2.Test/RandomNumber2.Test.csproj /p:Configuration=Release

    - name: Run MSTest tests
      run: msbuild RandomNumber2.Test/RandomNumber2.Test.csproj /p:Configuration=Release /t:VSTest
      shell: pwsh
