name: .NET Framework CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    # Restore huvudprojekt (Classic .NET Framework)
    - name: Restore NuGet packages (Main)
      run: msbuild RandomNumber2/RandomNumber2/RandomNumber2.csproj /t:Restore

    # Bygg huvudprojekt
    - name: Build main project
      run: msbuild RandomNumber2/RandomNumber2/RandomNumber2.csproj /p:Configuration=Release

    # Bygg testprojekt (SDK-style)
    - name: Build test project
      run: dotnet build RandomNumber2/RandomNumber2.Test/RandomNumber2.Test.csproj --configuration Release

    # Kör tester
    - name: Run unit tests
      run: dotnet test RandomNumber2/RandomNumber2.Test/RandomNumber2.Test.csproj --configuration Release --no-build

    # Optional: StyleCop analys
    - name: Run StyleCop analysis
      run: dotnet build RandomNumber2/RandomNumber2.Test/RandomNumber2.Test.csproj /p:TreatWarningsAsErrors=false
